---
version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 8
  complex-logic:
    enabled: true
    config:
      threshold: 20
  file-lines:
    enabled: true
    config:
      threshold: 500
  method-complexity:
    enabled: true
    config:
      threshold: 10
  return-statements:
    enabled: true
    config:
      threshold: 10
exclude_patterns:
  - ".circleci/"
  - "audiostack/tests/"
