---
config_blocks:
  only_tags: &only_tags
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v[0-9]+(\.[0-9]+)*$/

version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  unit-tests:
    docker:
      - image: cimg/python:3.8
    environment:
      CC_TEST_REPORTER_ID:
        71180b302f2a9ac17cbadc4430c26ef4081672918f2158896af78b37b95b7c00
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: --no-interaction --no-ansi
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L \
            https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64\
             > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: "unit-tests"
          command: |
            ./cc-test-reporter before-build
            export AUDIO_STACK_DEV_KEY=$AFLR_API_KEY_PROD_TEST
            poetry run task test
            ./cc-test-reporter after-build \
            --coverage-input-type coverage.py --exit-code $?
  lint:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: --no-interaction --no-ansi
      - run:
          name: "unit-tests"
          command: |
            poetry run task lint-check
  publish:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: --no-interaction --no-ansi --only main
      - run:
          name: "publish"
          command: |
            python3 increment_version.py
            cat audiostack/__init__.py
            poetry build
            poetry publish -u __token__ -p $PIP_AUDIOSTACK_TOKEN
          # You can find the token to publish to pypi here
          # https://eu-west-1.console.aws.amazon.com/systems-manager/parameters/pypi-m2m-token/description?region=eu-west-1&tab=Table#list_parameter_filters=Name:Contains:py

workflows:
  main-workflow:
    jobs:
      - unit-tests:
          context: aws
      - lint:
          context: aws

  publish:
    jobs:
      - unit-tests:
          <<: *only_tags
          context: aws
      - lint:
          <<: *only_tags
          context: aws
      - publish:
          <<: *only_tags
          context: aws
