config_blocks:
  only_tags: &only_tags
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v[0-9]+(\.[0-9]+)*$/

version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  unit-tests:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: audiostack/tests/requirements.txt
          pkg-manager: pip
      - run:
          name: "units"
          command: |
            export AUDIO_STACK_DEV_KEY=$AFLR_API_KEY_PROD_2

            python3 -m pytest audiostack/tests/ -v

  publish:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: "units"
          command: |
            python3 increment_version.py
            cat audiostack/__init__.py
            sh publish_ci.sh

workflows:
  main-workflow:
    jobs:
      - unit-tests:
          # filters:
          #   branches:
          #     only:
          #       - main
          context: aws

  publish:
    jobs:
      - unit-tests:
          <<: *only_tags
          context: aws
      - publish:
          <<: *only_tags
          context: aws
